FROM ghcr.io/fact0rn/sieverdispersion:sieverdispersion-base-gpu
# FROM sieverdispersion-base-gpu

COPY . /tmp/SieverDispersion

ENV SIEVER_MODE=1

WORKDIR /tmp/SieverDispersion
CMD ["/tmp/SieverDispersion/main.py"]
